### ISSUE TITLE
How to manually start ingest process

### ISSUE THREAD

**Issue by metasim** [sat-utils/sat-api#52]
I've just used `kes` to create my own instance of sat-api, and am attempting to create an initial baseline catalog.  Here's what I've attempted to do to, and am wondering if some advice might be shared.

I see that this process is usually initiated by a cron-type CloudWatch event, which triggers one of the state machine step functions. So I've tried manually starting an execution via the Step Functions console using input such as the following (as gleaned from the cron even input):

```json
{
    "satellite": "landsat",
    "arn": "arn:aws:states:us-east-1:123456:stateMachine:LandsatMetadataProcessorStateMachine-abcdefg",
    "maxFiles": 8,
    "maxLambdas": 10,
    "linesPerFile": 300
}
```

The step function error I get is:

```json
{
  "error": "Lambda.Unknown",
  "cause": "The cause could not be determined because Lambda did not return an error type."
}
```

Digging into the CloudWatch logs, I find this:

```console
START RequestId: 938285c1-83b8-41c9-b04c-8143d64b99e1 Version: $LATEST
2018-07-10T15:55:37.200Z	938285c1-83b8-41c9-b04c-8143d64b99e1
{
    "satellite": "landsat",
    "arn": "arn:aws:states:us-east-1:123456:stateMachine:LandsatMetadataProcessorStateMachine-abcdefg",
    "maxFiles": 8,
    "maxLambdas": 10,
    "linesPerFile": 300
}
2018-07-10T15:55:37.305Z	938285c1-83b8-41c9-b04c-8143d64b99e1	connected to elasticsearch
2018-07-10T15:55:37.308Z	938285c1-83b8-41c9-b04c-8143d64b99e1	Processing s3://undefined/undefined0.csv
2018-07-10T15:55:37.319Z	938285c1-83b8-41c9-b04c-8143d64b99e1	MissingRequiredParameter: Missing required key 'Bucket' in params
at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)
at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:61:14)
at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)
at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)
at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:125:42)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:85:9
at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:320:7)
at /var/runtime/node_modules/aws-sdk/lib/config.js:338:9
END RequestId: 938285c1-83b8-41c9-b04c-8143d64b99e1
REPORT RequestId: 938285c1-83b8-41c9-b04c-8143d64b99e1	Duration: 209.98 ms	Billed Duration: 300 ms Memory Size: 1024 MB	Max Memory Used: 101 MB	
RequestId: 938285c1-83b8-41c9-b04c-8143d64b99e1 Process exited before completing request
```

The `s3://undefined/undefined0.csv` line stands out to me. Note that my `.kes/config.yml` file has been updated to something like:

```yaml
default:
  ...
  buckets:
    internal: my-real-bucket
```

so I'm not sure where else I'm supposed to put bucket info. And am somewhat stuck as to how to get a test instance running. 

Any pointers are appreciated!

**Comment by matthewhanson** [comment]
Hmm, this is peculiar @metasim , you actually did the right thing and that's how I back populate the catalog, just manually call the step function. And then when I'm really sure it's working I remove the "maxFiles" parameter and it ingests all of them (a time consuming process, especially for sentinel).

I assume you are using the develop branch? And the only change you made was to the bucket name right?

I'll look into this more tonight and see if I can come up with anything.

As an aside, @scisco is currently working on improving the deployment process to make it easier for new deployments, and I'd like to make it easier to do the original population as well, but first we'll need to get STAC flat catalogs for Landsat and Sentinel so they can be ingested far quicker.

Thanks for filing the issue, I'll report back with any insight.

**Comment by matthewhanson** [comment]
Actually, one more thing @metasim , the payload you posted is correct, but you want to invoke the Ingest Lambda with that, not the Landsat lambda. I can't tell from what you posted which one you had invoked.

The ingest lambda will split up the input CSV then fire off a bunch of the Landsat processor step functions to process all of them.

**Comment by metasim** [comment]
@matthewhanson I super appreciate the tips!

Yes, on the `develop` branch and only changed the bucket name and the IP address in the `.env` file. However, I need to confirm that I ran the right lambda. I'll follow up.

**Comment by metasim** [comment]
@matthewhanson It looks likely that I may have been invoking the wrong Lambda; but now I get this when I call the ingest (which in my case is named `sat-api-v1-dev-ingest`):

```console
START RequestId: 18fe9839-8492-11e8-8966-a3aba15a2b8f Version: $LATEST
2018-07-10T22:39:26.379Z	18fe9839-8492-11e8-8966-a3aba15a2b8f	ingest event:  {"satellite":"landsat","arn":"arn:aws:states:us-east-1:12345:stateMachine:LandsatMetadataProcessorStateMachine-abcde","maxFiles":8,"maxLambdas":10,"linesPerFile":300}
2018-07-10T22:39:26.380Z	18fe9839-8492-11e8-8966-a3aba15a2b8f	TypeError: _.get is not a function
    at module.exports.module.exports.handler (/var/task/index.js:175033:20)
END RequestId: 18fe9839-8492-11e8-8966-a3aba15a2b8f
REPORT RequestId: 18fe9839-8492-11e8-8966-a3aba15a2b8f	Duration: 40.60 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 103 MB	
RequestId: 18fe9839-8492-11e8-8966-a3aba15a2b8f Process exited before completing request
```

**Comment by metasim** [comment]
Here's what line `175033` ends up resolving to:

<img width="514" alt="screen shot 2018-07-10 at 6 49 55 pm" src="https://user-images.githubusercontent.com/131013/42541832-14145f06-8472-11e8-82e7-500b905e598b.png">

I don't know enough about JavaScript to understand what `_` resolves to...

**Comment by fredliporace** [comment]
@metasim found the same message a while ago, had to include
```javascript
const _ = require('lodash')
```
in the start of the file

**Comment by metasim** [comment]
After applying #53 (thanks @fredliporace !!!), I was able to manually invoke the lambda!

```console

START RequestId: 55708037-84a0-11e8-9203-7dd4354b53d3 Version: $LATEST
2018-07-11T00:21:20.770Z	55708037-84a0-11e8-9203-7dd4354b53d3	ingest event:
{
    "satellite": "landsat",
    "arn": "arn:aws:states:us-east-1:12345:stateMachine:LandsatMetadataProcessorStateMachine-abcde",
    "maxFiles": 8,
    "maxLambdas": 10,
    "linesPerFile": 300
}

2018-07-11T00:21:26.489Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 250 files
2018-07-11T00:21:31.342Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 500 files
2018-07-11T00:21:36.192Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 750 files
2018-07-11T00:21:41.089Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 1000 files
2018-07-11T00:21:45.989Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 1250 files
2018-07-11T00:21:50.789Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 1500 files
2018-07-11T00:21:55.791Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 1750 files
2018-07-11T00:22:00.925Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 2000 files
2018-07-11T00:22:05.750Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 2250 files
2018-07-11T00:22:10.827Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 2500 files
2018-07-11T00:22:15.644Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 2750 files
2018-07-11T00:22:20.784Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 3000 files
2018-07-11T00:22:25.931Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 3250 files
2018-07-11T00:22:31.112Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 3500 files
2018-07-11T00:22:35.629Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 3750 files
2018-07-11T00:22:40.443Z	55708037-84a0-11e8-9203-7dd4354b53d3	uploaded 4000 files
2018-07-11T00:22:44.284Z	55708037-84a0-11e8-9203-7dd4354b53d3	4205 total files
2018-07-11T00:22:44.284Z	55708037-84a0-11e8-9203-7dd4354b53d3	Invoking 8 batches of Lambdas of 1 files each with 0 extra (Files 4199-4206)
2018-07-11T00:22:44.413Z	55708037-84a0-11e8-9203-7dd4354b53d3	launched
{
    "stateMachineArn": "arn:aws:states:us-east-1:12345:stateMachine:LandsatMetadataProcessorStateMachine-abcde",
    "input": "{\"bucket\":\"foobar-stac-1\",\"key\":\"sat-api-v1-dev/ingest/landsat/\",\"currentFileNum\":4200,\"lastFileNum\":4200,\"arn\":\"arn:aws:states:us-east-1:12345:stateMachine:LandsatMetadataProcessorStateMachine-abcde\"}",
    "name": "ingest_4200_1531268564295"
}

2018-07-11T00:22:44.426Z	55708037-84a0-11e8-9203-7dd4354b53d3	launched
{
    "stateMachineArn": "arn:aws:states:us-east-1:abcde:stateMachine:LandsatMetadataProcessorStateMachine-abcde",
    "input": "{\"bucket\":\"foobar-stac-1\",\"key\":\"sat-api-v1-dev/ingest/landsat/\",\"currentFileNum\":4199,\"lastFileNum\":4199,\"arn\":\"arn:aws:states:us-east-1:12345:stateMachine:LandsatMetadataProcessorStateMachine-abcde\"}",
    "name": "ingest_4199_1531268564291"
}

...

END RequestId: 55708037-84a0-11e8-9203-7dd4354b53d3
REPORT RequestId: 55708037-84a0-11e8-9203-7dd4354b53d3	Duration: 84173.84 ms	Billed Duration: 84200 ms Memory Size: 1024 MB	Max Memory Used: 233 MB	
```

**Comment by matthewhanson** [comment]
Thanks @fredliporace !  

Strange missing a require, that shouldn't have been working for me, and yet it does somehow...
